services:
  fluent-connect-main:
    build:
      context: .
      dockerfile: mocks/fluent-connect-main/Dockerfile
    environment:
      VITE_FLUENT_HOSTED_SESSION_ENDPOINT: ""
    ports:
      - "5173:5173"

  chess-app:
    build:
      context: .
      dockerfile: apps/chess/Dockerfile
    environment:
      VITE_CHESS_BOT_CONTROL_ENDPOINT: /chess-bot
    ports:
      - "8050:8050"
