packages:
  - "packages/*"
  - "apps/*"
  - "mocks/*"
overrides:
  '@wagmi/connectors': 5.9.9
  viem: 2.52.0
allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  esbuild: true
  keccak: true
  utf-8-validate: true
